# Generated by Django 3.1.1 on 2020-12-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtersubmission',
            name='acousticness_atleast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filtersubmission',
            name='danceability_atleast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filtersubmission',
            name='duration_ms_atleast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filtersubmission',
            name='energy_atleast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filtersubmission',
            name='instrumentalness_atleast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filtersubmission',
            name='liveness_atleast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filtersubmission',
            name='loudness_atleast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filtersubmission',
            name='speechiness_atleast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filtersubmission',
            name='tempo_atleast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filtersubmission',
            name='valence_atleast',
            field=models.BooleanField(default=True),
        ),
    ]
