# Generated by Django 3.1.1 on 2020-12-14 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201213_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtersubmission',
            name='acousticness_val',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='filtersubmission',
            name='danceability_val',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='filtersubmission',
            name='energy_val',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='filtersubmission',
            name='instrumentalness_val',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='filtersubmission',
            name='liveness_val',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='filtersubmission',
            name='loudness_val',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(-60)]),
        ),
        migrations.AlterField(
            model_name='filtersubmission',
            name='speechiness_val',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='filtersubmission',
            name='tempo_val',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='filtersubmission',
            name='valence_val',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0)]),
        ),
    ]
